<p>Dear {{ $booking->participant->name }},</p>
<p>We are pleased to inform you that your payment has been successfully confirmed. Thank you for booking with <strong>SistemKami</strong>.</p>

<p><strong>Booking Summary</strong></p>
<ul>
    <li><strong>Booking Code:</strong> {{ $booking->booking_code }}</li>
    <li><strong>Package Name:</strong> {{ $booking->package->name }}</li>
    @if($booking->vendorTimeSlots && $booking->vendorTimeSlots->count())
        @foreach ($booking->vendorTimeSlots as $slot)
            <li>
                <strong>Booked Date:</strong>
                {{ \Carbon\Carbon::parse($slot->booked_date_start)->format('d M Y') }}
            </li>

            <li>
                <strong>Booked Time:</strong>
                {{ \Carbon\Carbon::parse($slot->booked_time_start)->format('h:i A') }}
                -
                {{ \Carbon\Carbon::parse($slot->booked_time_end)->format('h:i A') }}
            </li>
        @endforeach
    @endif



    <li><strong>Status:</strong> {{ ucfirst($booking->status) }}</li>
    <li><strong>Total Price:</strong> RM {{ number_format($booking->final_price, 2) }}</li>
    @if($booking->discount)
    <li><strong>Discount:</strong> RM {{ number_format($booking->discount, 2) }}</li>
    @endif
    @if($booking->payment_type == 'deposit')
    <li><strong>Deposit Paid:</strong> RM {{ number_format($booking->paid_amount, 2) }}</li>
    <li><strong>Remaining Balance:</strong> RM {{ number_format($booking->final_price - $booking->paid_amount, 2) }}</li>
    @endif
</ul>

<p>If you have any questions or need further assistance, feel free to contact our support team.</p>

<p>Best regards,<br><strong>SistemKami Team</strong></p>

<p><em>Please do not reply to this email. This is an automated message generated by the SistemKami platform.</em></p>

