<p>Dear {{ $booking->participant->name }},</p>

<p>We are pleased to inform you that your payment has been successfully confirmed. Thank you for booking with <strong>SistemKami</strong>.</p>

@if ($isEligibleForShirt)
    <p>🎉 Congratulations! You are among the first 100 participants eligible to receive a shirt for this event.</p>
    <p>The shirt will be provided according to the size you selected: <strong>{{ $booking->extra_info['shirt_size'] ?? 'Not specified' }}</strong>.</p>
@endif

<p><strong>Booking Summary</strong></p>
<ul>
    <li><strong>Booking Code:</strong> {{ $booking->booking_code }}</li>
    <li><strong>Status:</strong> {{ ucfirst($booking->status) }}</li>
    <li><strong>Total Price:</strong> RM {{ number_format($booking->final_price, 2) }}</li>
    @if ($isEligibleForShirt)
        <li><strong>Shirt Size:</strong> {{ $booking->extra_info['shirt_size'] ?? 'Not specified' }}</li>
    @endif
</ul>

<p><strong>Ticket Details</strong></p>

@foreach ($booking->bookingTickets as $ticket)
    <div style="margin-bottom: 20px; padding: 10px; border: 1px solid #ccc;">
        <p><strong>Ticket Code:</strong> {{ $ticket->ticket_code }}</p>
        <p><strong>Attendee Name:</strong> {{ $ticket->participant_name }}</p>
        <p><strong>Attendee Email:</strong> {{ $ticket->participant_email }}</p>
        <p><strong>Status:</strong> {{ ucfirst($ticket->status) }}</p>
        <p><strong>Ticket Price:</strong> RM {{ number_format($ticket->price, 2) }}</p>
    </div>
@endforeach

<p>If you have any questions or need further assistance, feel free to contact our support team.</p>

<p>Best regards,<br><strong>SistemKami Team</strong></p>

<p><em>Please do not reply to this email. This is an automated message generated by the SistemKami platform.</em></p>

